### ISSUE TITLE
Impossible to build error handling in current version

### ISSUE THREAD

**Issue by ahockersten** [pholactery/eventsourcing#4]
I'm not sure if this is me misunderstanding, but I expect to be able to build a `handle_command` function that looks like this:
```
  fn handle_command(state: &Self::State, cmd: Self::Command) -> Result<Vec<Self::Event>, Error> {
    match (state, &cmd) {
      (PlayerData {generation: 0, ..}, PlayerCommand::Create {..}) => Ok(vec![cmd.into()]),
      (_, PlayerCommand::Create {..}) => Err(Error{kind: CommandFailure("Create is only valid on generation 0".to_string())})
    }
```
In other words, if this is not the first generation, a "create" event is invalid. However, as the `kind` field in `eventsourcing::Error` is not exported, it is not possible to set it, and no other constructor for `eventsourcing::Error` exists.

https://github.com/robscllc/eventsourcing seems to contain a fix for this (along with some other improvements).

**Comment by autodidaddict** [comment]
I've updated and taken all the open PRs, so this should be possible with `kind` being public now.
