### ISSUE TITLE
documentation build failed

### ISSUE THREAD

**Issue by Aedius** [pholactery/eventsourcing#7]
Hello, 

i dont know if you are aware and working on it, but crates.io cannot generate the documentation properly :

https://docs.rs/crate/eventsourcing/0.1.4/builds

Thanks for the lib

**Comment by autodidaddict** [comment]
No I wasn't aware of that. I'll try and figure out what's happening and fix
it. Thanks for letting me know

**Comment by autodidaddict** [comment]
Fixed in 0.1.5
